#!/bin/bash
helm upgrade \
    --install \
    --namespace=gpu-operator \
    --create-namespace \
    --wait \
    --set driver.enabled=false \
    --set toolkit.enabled=false \
    --values=values.yaml\
    gpu-operator \
    nvidia/gpu-operator

