apiVersion: v1
kind: Pod
metadata:
  name: nvidia-cuda
spec:
  containers:
  - name: nvidia-cuda
    image: nvidia/cuda:11.7.0-base-ubuntu20.04
    args:
      - nvidia-smi
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
