- name: Preparing to install k0s
  hosts: linux
  remote_user: magus
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: missing pkgs 
      shell: |
        apt-get update
        apt-get install -y iptables arptables ebtables open-iscsi

    - name: updating alternatives
      shell: |
        update-alternatives --set iptables /usr/sbin/iptables-nft
        update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
        update-alternatives --set arptables /usr/sbin/arptables-nft
        update-alternatives --set ebtables /usr/sbin/ebtables-nft

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        seconds: 20

    - name: Restart ha
      shell: |
        reboot now
