- name: configuring haproxy
  hosts: loadbalancer
  remote_user: magus
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Install haproxy
      shell: |
        apt update
        apt install -y haproxy

    - name: Copy file from control node to managed node
      copy:
        src: ./haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0600'

    - name: Restart ha
      shell: |
        sudo systemctl restart haproxy
