#!/bin/bash
start_time=$(date +%s.%N)
SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd $SCRIPT_DIR
echo "$SCRIPT_DIR"
cd 0-create_cluster/proxmox_k0s/0-provisioning/
sh create.sh
cd ..
# pshel
echo "Dando uma dormida para assentar a poeira"
sleep 20
cd 1-creating/0-prepare_all/
sh run.sh
cd ..
echo "Dando uma dormida para assentar a poeira"
sleep 20
cd 1-lb_hap
sh run.sh
cd ..
echo "Dando uma dormida para assentar a poeira"
sleep 20
cd 2-cluster
sh create_cluster.sh
chmod 0600 ~/.kube/config
cd $SCRIPT_DIR
cd 1-configure_cluster/0-helm_config/
sh helm_config
cd ..
cd 1-nginx-ingress/
sh create
cd ..
cd 2-certmanager
sh create
cd ..
kubectl apply -f 0-helm_config/mlb.yaml
cd 3-rancher
sh create
cd ..
cd 3-longhorn
sh create
cd ..
echo "Dando uma dormida para assentar a poeira"
sleep 60
cd 4-evolution_api
sh create
cd ..
cd 4-baserow
sh create
cd ..
cd 4-n8n
sh create
cd ..
cd 5-ollama
sh create
cd ..
cd 4-chatwoot
sh create
cd ..
cd ..
end_time=$(date +%s.%N)
execution_time=$(bc -l <<< "scale=3; $end_time - $start_time")
echo "Execution time: $execution_time seconds"
echo "Execution time: $execution_time seconds" > c.time.log
sh ./fire
