#!/bin/bash
execution_path=$(pwd)
start_time=$(date +%s.%N)
SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd $SCRIPT_DIR
echo "$SCRIPT_DIR"
cd 0-create_cluster/k0s/0-provisioning/
sh destroy.sh
rm -r ~/.kube
end_time=$(date +%s.%N)
execution_time=$(bc -l <<< "scale=3; $end_time - $start_time")
echo "Execution time: $execution_time seconds"
echo "Execution time: $execution_time seconds" > $execution_path/d.time.log
