#!/bin/bash
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.15.3 \
  --set crds.enabled=true \
  --set prometheus.enabled=false 
sh ./scripts/create_api_secret
kubectl apply -f issuer_dns0.yaml
